feat: [sc-143546] Python Client Lib Update for Verify APIs and removing Company and EmailVerification support
fullcontact/fullcontact-python-client pull request #18
Opened 2022-06-02 10:26 UTC by MananMukim

Story details: https://app.shortcut.com/fullcontact/story/143546

2022-06-15 09:57 UTC, prakhar-j requested changes
Some minor comments, Rest looks good. Thanks!

2022-06-15 09:57 UTC, prakhar-j commented on README.md
> +Resolve, Tags, Audience APIs. FullContact API Documentation is available
We can add that it supports Verify and Permission APIs

2022-06-15 09:57 UTC, prakhar-j commented on README.md
> +> Verify API Documentation: https://docs.fullcontact.com/docs/multi-field-request-verify
Link can be https://docs.fullcontact.com/docs/verify-overview

2022-06-15 09:57 UTC, prakhar-j commented on fullcontact/__about__.py
> +__version__ = "3.2.0"
Version should be 4.0.0, as it has breaking changes

2022-06-21 10:29 UTC, prakhar-j requested changes

2022-06-21 10:29 UTC, prakhar-j commented on README.md
> +* `get_extended()`: _dict_ - All Epsilon data
Please replace with: "All Extended data"

2022-06-28 19:24 UTC, jidler approved these changes

2022-07-01 07:10 UTC, merged